[package]
name = "authentication_tui"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/IanTeda/authentication_tui"
description = "A TUI application front end for the Authentication Mircorsevice"
keywords = ["authentication", "tui", "ratatui", "tonic client"]

[dependencies]
cargo-make = "0.37.14"
chrono = "0.4.38"
color-eyre = "0.6.3"
config = "0.14.0"
crossterm = { version = "0.28.1", features = ["event-stream"] }
directories = "5.0.1"
futures = "0.3.30"
http = "1.1.0"
lazy_static = "1.5.0"
prost = "0.13"
ratatui = "0.27.0"
serde = "1.0.204"
thiserror = "1.0.63"
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.17"
tonic = { version = "0.12.0", features = ["prost"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
tonic-build = { version = "0.12", features = ["prost"] }
