###############################################################################
## CARGO MAKEFILE
## Rust task runner and build tool.
##
## https://github.com/sagiegurari/cargo-make
## $ cargo install --force cargo-make
## ############################################################################
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = ["format", "build", "test"]

## https://github.com/watchexec/cargo-watch
[tasks.watch]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "--clear", "--watch", "src", "--exec", "run"]
